CREATE TABLE course_registration
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT,
    course_id  BIGINT,
    CONSTRAINT pk_courseregistration PRIMARY KEY (id)
);

ALTER TABLE course_registration
    ADD CONSTRAINT FK_COURSEREGISTRATION_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE course_registration
    ADD CONSTRAINT FK_COURSEREGISTRATION_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);