CREATE TABLE profesor
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_profesor PRIMARY KEY (id)
);

ALTER TABLE course_registration
    ADD COLUMN profesor_id int;

ALTER TABLE course_registration
    ADD CONSTRAINT FK_COURSEREGISTRATION_ON_PROFESOR FOREIGN KEY (profesor_id) REFERENCES profesor (id);